 #  maintain versioning information

#    name - The name of the application
#    executable - (Optional) The name of the file to be called to begin application execution
#    version - The version number of the application
#    author - The author of the application

name = "my-mission-app"
executable = "my-mission-app.py"
version = "1.0.1"
author = "Manuel Lindo"
